/*
	Measures Exploration 

	- Calculate the key metric of the business (Big Numbers)
	- Highest Level Of Aggregation | Lowest Level Of Details

	Magnitude

	- Compare the measure values by categories.
	- It helps us understand the importance of different categories.
	- Formula/Method: [Measure] BY [Dimension]
*/

-- 1. Measures Exploration 

-- Find the Total Sales
Select SUM(sales_amount) as Total_Sales_Amt
From gold.fact_sales

-- Find the average Selling Price
Select 
		AVG(price) as avg_price 
From gold.fact_sales

-- Find the total number of orders
Select Count(Distinct order_number) as total_orders From gold.fact_sales

-- Find the total number of products
Select Count(product_key) as total_products
From gold.dim_products

-- Find the total number of customers
Select Count(customer_key) as total_customers
From gold.dim_customers

-- Find the total number of customers that has placed an order
Select Count(Distinct customer_key) as total_customers_placed_order
From gold.dim_customers

-- Generate a report that shows all key metrics of the business

Select 'Total Sales' as measure_name, SUM(sales_amount) as measure_value From gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(sales_quantity) FROM gold.fact_sales
UNION ALL
SELECt 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECt 'Total No. Of Orders', COUNT(DISTINCT order_number) from gold.fact_sales
UNION ALL
SELECT 'Total No. Of Products', COUNT(product_name) FROM gold.dim_products
UNION ALL
SELECT 'Total No. Of Customers', COUNT(customer_key) from gold.dim_customers

-- 2. Magnitude Exploration

-- Find total customer by countries
SELECT DISTINCT(country) AS 'country', COUNT(customer_key) AS 'Total Customer' 
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

-- Find total customer by gender
SELECT DISTINCT(gender) as 'Gender', Count(customer_key) as 'Total Customer'
FROM gold.dim_customers
GROUP BY gender
Order By Count(customer_key) Desc;

-- Find total customer by age group
WITH CustomerAge AS (
    SELECT
        customer_key,
        birthdate,
        DATEDIFF(YEAR, birthdate, GETDATE())
        - CASE
              WHEN DATEADD(YEAR, DATEDIFF(YEAR, birthdate, GETDATE()), birthdate) > GETDATE()
              THEN 1
              ELSE 0
          END AS age
    FROM gold.dim_customers
    WHERE birthdate IS NOT NULL
)
SELECT
    CASE
        WHEN age < 18 THEN '<18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    COUNT(*) AS customer_count
FROM CustomerAge
GROUP BY
    CASE
        WHEN age < 18 THEN '<18'
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 45 THEN '36-45'
        WHEN age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END
ORDER BY age_group;

-- Find total products by category
Select category, COUNT(product_key) as 'Total Products'
FROM gold.dim_products
GROUP BY category;

-- What is the average costs in each category?
Select category, AVG(cost) as 'Avg Cost'
FROM gold.dim_products
GROUP BY category
ORDER BY 'Avg Cost' DESC;

-- What is the total revenue generated for each category?
SELECT 
        dp.category as category,
        SUM(fs.sales_amount) as 'Total Revenue'
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_products as dp
ON fs.product_key = dp.product_key
Group BY dp.category
Order By dp.category ASC

-- Find total revenue generated by each customer
SELECt
        dc.customer_key,
        dc.first_name,
        dc.last_name,
        SUM(fs.sales_amount) as total_revenue
FROM gold.fact_sales as fs
LEFT JOIN gold.dim_customers as dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
        dc.country as 'Country',
        SUM(fs.sales_quantity) as total_sold_items
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country 
ORDER BY dc.country;

